version: '3.4'

services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: world-of-books-backend-container
    image: world-of-books-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80
      - 4343:443
 

  